dist: xenial
language: python
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install pycodestyle codecov
  - python setup.py install
script:
  - make lint
  - make coverage
after_success:
  - codecov
